const projects = [
    {
        id: 1,
        title: 'Project Title 1',
        description: 'Project Description 1',
        created_on: new Date().toDateString(),
        manager: 'Manager 1',
        is_archived: false,
        developers: [],
        team: 'Team 1',
        subscribers: [],
        open_tickets: 3,
    },
    {
        id: 2,
        title: 'Project Title 2',
        description: 'Project Description 2',
        created_on: new Date().toDateString(),
        manager: 'Manager 1',
        is_archived: false,
        developers: [],
        team: 'Team 1',
        subscribers: [],
        open_tickets: 3,
    },
    {
        id: 3,
        title: 'Project Title 3',
        description: 'Project Description 3',
        created_on: new Date(2020, 9, 15, 11).toDateString(),
        manager: 'Manager 2',
        is_archived: false,
        developers: [],
        team: 'Team 1',
        subscribers: [],
        open_tickets: 5,
    },
    {
        id: 4,
        title: 'Project Title 4',
        description: 'Project Description 4',
        created_on: new Date().toDateString(),
        manager: 'Manager 2',
        is_archived: true,
        developers: [],
        team: 'Team 1',
        subscribers: [],
        open_tickets: 6,
    }
]

export default projects