const tickets = [
    {
        id: 1,
        title: 'Fix bugs',
        description: 'Fix bugs please!',
        user: 'Submitter 1',
        developers: [],
        priority: 'Urgent',
        created_on: new Date(2020, 5, 15, 11).toDateString(),
        updated_on: new Date().toDateString(),
        team: 'Team 1',
        project_id: 1,
        status: 'open',
        resolution: null,
    },
    {
        id: 2,
        title: 'Front end',
        description: 'Frontend work',
        user: 'Submitter 2',
        developers: ['Member 1', 'Member 2',],
        priority: 'High',
        created_on: new Date(2020, 1, 11, 11).toDateString(),
        updated_on: new Date().toDateString(),
        team: 'Team 1',
        project_id: 1,
        status: 'open',
        resolution: null,
    },
    {
        id: 3,
        title: 'Other project ticket',
        description: 'Fix bugs please!',
        user: 'Submitter 1',
        developers: null,
        priority: 'Urgent',
        created_on: new Date(2020, 5, 15, 11).toDateString(),
        updated_on: new Date().toDateString(),
        team: 'Team 1',
        project_id: 3,
        status: 'open',
        resolution: null,
    },
    {
        id: 4,
        title: 'Closed ticket',
        description: 'Fix bugs please!',
        user: 'Submitter 1',
        developers: null,
        priority: 'Urgent',
        created_on: new Date(2020, 5, 15, 11).toDateString(),
        updated_on: new Date().toDateString(),
        team: 'Team 1',
        project_id: 1,
        status: 'closed',
        resolution: 'Fixed',
    },
]

export default tickets